stages:
  - create_vis
  - build_linux
  - build_esp
  - build_nanomind
  - test_linux

create_vis:
  stage: create_vis
  script:
    - echo "Creating Visualizations"
  only:
    - master

build_linux:
  stage: build_linux
  script:
    - echo "Building in Linux"
  only:
    - master
    
build_esp:
  stage: build_esp
  script:
    - echo "Building in esp32"
  only:
    - master
    
build_nanomind:
  stage: build_nanomind
  script:
    - echo "Building in nanomind"
  only:
    - master

test_linux:
  stage: test_linux
  script:
    - echo "Testing in Linux"
  only:
    - master




