
stages:
  - create_vis
  - build_linux
  - build_esp
  - build_nanomind
  - test_linux

create_vis:
  stage: create_vis
  script:
    - echo "Creating Visualizations"
    - whoami
    - pwd
    - last_commit=`git log -1 --pretty=%h`
    - echo $HOME
    - cd $HOME/Analyse/SUCHAI-Flight-Software
    - git pull origin master
    - cd ../Analyse
    - pwd
    - python3 suchai_analysis.py ../SUCHAI-Flight-Software --hash $last_commit --svg
#    - commit_file_="find . -maxdepth 1 -name "*\$last_commit.html" -print"
#    - commit_file=`\$commit_file_`
#    - svg_file_="find . -maxdepth 1 -name "*\$last_commit.svg" -print"
#    - svg_file=`\$svg_file_`
#    - cp -f \$commit_file /home/ubuntu/SpelDataServer/public/viz_html/
#    - rm \$commit_file
#    - echo http://data.spel.cl/viz_html\${commit_file#"."}
#    - cp -f \$svg_file /home/ubuntu/SpelDataServer/public/viz_svg/
#    - cp -f \$svg_file /home/ubuntu/SpelDataServer/public/viz_svg/last.svg
#    - rm \$svg_file
#    - echo http://data.spel.cl/viz_svg\${svg_file#"."}
  only:
    - cicd_test

build_linux:
  stage: build_linux
  script:
    - echo "Building in Linux"
  only:
    - cicd_test
    
build_esp:
  stage: build_esp
  script:
    - echo "Building in esp32"
  only:
    - cicd_test
    
build_nanomind:
  stage: build_nanomind
  script:
    - echo "Building in nanomind"
  only:
    - cicd_test

test_linux:
  stage: test_linux
  script:
    - echo "Testing in Linux"
  only:
    - master




